/**
 * Copyright (c) HashiCorp, Inc.
 * SPDX-License-Identifier: MPL-2.0
 */

// generated by cdktf get
Object.defineProperty(exports, 'cluster', { get: function () { return require('./cluster'); } });
Object.defineProperty(exports, 'clusterRootToken', { get: function () { return require('./cluster-root-token'); } });
Object.defineProperty(exports, 'snapshot', { get: function () { return require('./snapshot'); } });
Object.defineProperty(exports, 'dataHcsAgentHelmConfig', { get: function () { return require('./data-hcs-agent-helm-config'); } });
Object.defineProperty(exports, 'dataHcsAgentKubernetesSecret', { get: function () { return require('./data-hcs-agent-kubernetes-secret'); } });
Object.defineProperty(exports, 'dataHcsCluster', { get: function () { return require('./data-hcs-cluster'); } });
Object.defineProperty(exports, 'dataHcsConsulVersions', { get: function () { return require('./data-hcs-consul-versions'); } });
Object.defineProperty(exports, 'dataHcsFederationToken', { get: function () { return require('./data-hcs-federation-token'); } });
Object.defineProperty(exports, 'dataHcsPlanDefaults', { get: function () { return require('./data-hcs-plan-defaults'); } });
Object.defineProperty(exports, 'provider', { get: function () { return require('./provider'); } });

